---

- name: set default instance size
  set_fact: 
    default_size: "{{ _instance_type.size | default(__default_size) }}"

- name: "create EC2 instance for {{ _instance.name }}"
  ec2:
    id: "{{ _instance.short }}-{{ idx }}/{{ ec2_lab_count }}"
    key_name: "{{ ec2_pem_key_name }}"
    instance_type: "{{ _instance.size | default(default_size) }}"
    image: "{{ _instance_ami.image_id }}"
    vpc_subnet_id: "{{ ec2_subnet_ids[_instance.network] 
      | default(ec2_subnet_ids[0]) }}"
    assign_public_ip: "{{ _instance.public_ip | default(omit) }}"
    region: "{{ ec2_region }}"
    group: "{{ ec2_name_prefix }}-{{ _instance.short }}"
    volumes: "{{ _instance.volumes | default(omit) }}"
    wait: yes
    wait_timeout: 600
  register: _singlenet_instance
  tags: [always]

- name: "ensure tags for {{ _instance.name }}"
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ _singlenet_instance.instances[0].id }}"
    state: present
    tags:
      Name: "{{ _instance.tag_name | default(_instance.short) }}"
      Demo: "{{ ec2_name_prefix }}"
      Function: "{{ _instance.tag_function | default(__default_function) }}"
  register: _singlenet_tag_output
  until: _singlenet_tag_output is not failed
  retries: 10
  tags: [always]
