---

- name: register devices to route53 DNS 
  hosts: all
  roles: 
    - aws-route53
  vars_files:
    - vars/shared_vars.yml
  connection: local
  gather_facts: false
  tags: [route53, dns]
  
- name: post provisioning AWS instance Bastion Server
  hosts: function_bastion
  vars: 
    ansible_ssh_user: centos
    ansible_python_interpreter: '/usr/bin/python'
  vars_files:
    - vars/shared_vars.yml
  roles: 
    - bastion-server
  tags: [bastion]

- name: post provisioning AWS instance Ansible Tower
  hosts: function_tower
  vars: 
    ansible_python_interpreter: '/usr/libexec/platform-python'
  vars_files:
    - vars/shared_vars.yml
    - vars/aws-vault.yml
  roles: 
    - ansible-tower-install 
  tags: [tower]

- name: post provisioning AWS F5
  hosts: function_loadbalancer
  vars:
    ansible_user: admin
  vars_files:
    - vars/shared_vars.yml
    - vars/aws-vault.yml
  roles:
    - aws-post-provision
  tags: [f5]
  gather_facts: no
  connection: local

  