---

- name: take variables from shared vars
  set_fact: 
    aws_pem_key_name: "{{ pem_key_name | default(omit) }}"
    aws_pem_key_location: "{{ pem_key_location | default(omit) }}"
    aws_pem_key: "{{ pem_key_location }}{{ pem_key_name }}.pem"
  when: pem_key_name is defined and pem_key_location is defined

- include_tasks:
    file: f5.yml
  when: tags.OS == 'f5'