__tower_credentials:
  - name: aws 
    kind: aws
    username: "{{ tower_aws_access_key }}"
    password: "{{ tower_aws_secret_key }}"
  - name: cisco ec2
    username: ec2-user
    kind: ssh
    ssh_key_data: "{{ lookup('file', tower_pem_key, errors='warn') }}"
  - name: centos
    username: centos
    kind: ssh
    ssh_key_data: "{{ lookup('file', tower_pem_key, errors='warn') }}"
  - name: virl_cisco
    username: cisco
    password: cisco123
    become_password: cisco123
    kind: ssh
  - name: aws_vault_file
    kind: vault
    vault_password: "{{ tower_aws_vault_password }}"
