
__tower_projects: 
  - name: network-lab
    scm_url: https://github.com/maxrainer/ansible-network-labs.git
    descripion: Network Labs for PoC and Workshops
    scm_clean: yes

__tower_credentials:
  - name: aws 
    kind: aws
    username: "{{ tower_aws_access_key }}"
    password: "{{ tower_aws_secret_key }}"
  - name: cisco ec2
    username: ec2-user
    kind: ssh
    ssh_key_data: "{{ lookup('file', tower_pem_key) }}"

__tower_inventories: 
  - name: aws net-demo
    description: dynamic inventory from AWS EC2 

__tower_inventory_sources:
  - name: ec2 net-demo
    source: scm
    source_project: network-lab
    credential: aws
    source_path: lab.aws_ec2.yml
    inventory: aws net-demo
    overwrite: yes
    update_on_launch: yes

__tower_groups:
  - name: function_router
    inventory: aws net-demo
    description: Cisco IOS Router 
    variables: "{{ lookup('file', role_path+'/files/function_router_vars.yml') }}"

__tower_job_template:
  - name: IOS Interface L3 Configuration
    description: sets admin status, ipv4 address, description
    job_type: run
    inventory: aws net-demo
    project: network-lab 
    playbook: aws_router.yml
    credential: cisco ec2
    job_tags: interface
  - name: IOS Interface L3 Rollback 
    description: reset Interfaces to default configuration
    job_type: run
    inventory: aws net-demo
    project: network-lab
    playbook: aws_router.yml 
    credential: cisco ec2
    job_tags: rollback, interface
    skip_tags: config
    



