---
# tower vars.yml 

__tower_venv_path: /opt/venvs
__tower_venvs:
  - name: genie
    pip: ['psutil','ansible','paramiko','genie==19.12','pyats==19.12','jmespath'] 

__tower_projects: 
  - name: network-lab
    scm_url: https://github.com/maxrainer/ansible-network-labs.git
    descripion: Network Labs for PoC and Workshops
    scm_clean: yes

__tower_credentials:
  - name: aws 
    kind: aws
    username: "{{ tower_aws_access_key }}"
    password: "{{ tower_aws_secret_key }}"
  - name: cisco ec2
    username: ec2-user
    kind: ssh
    ssh_key_data: "{{ lookup('file', tower_pem_key) }}"
  - name: centos
    username: centos
    kind: ssh
    ssh_key_data: "{{ lookup('file', tower_pem_key) }}"
#  no kind available for GitHub Access Token
#  - name: github access token


__tower_inventories: 
  - name: aws net-demo
    description: dynamic inventory from AWS EC2 

__tower_inventory_sources:
  - name: ec2 net-demo
    source: scm
    source_project: network-lab
    credential: aws
    source_path: lab.aws_ec2.yml
    inventory: aws net-demo
    overwrite: yes
    update_on_launch: yes

__tower_groups:
  - name: function_router
    inventory: aws net-demo
    description: Cisco IOS Router 
    variables: "{{ lookup('file', role_path+'/files/function_router_vars.yml') }}"
  - name: function_loadbalancer
    inventory: aws net-demo 
    description: F5 Big-IP 
    variables: "{{ lookup('template', role_path+'/templates/function_loadbalancer_vars.yml.j2') }}"
  - name: function_webserver
    inventory: aws net-demo
    description: needed as webserver to connect 
    variables: "{{ lookup('file', role_path+'/files/function_webserver_vars.yml') }}"

__tower_job_template:
  - name: IOS Interface L3 Configuration
    description: sets admin status, ipv4 address, description
    job_type: run
    inventory: aws net-demo
    project: network-lab 
    playbook: aws_router.yml
    credential: cisco ec2
    job_tags: interface
  - name: IOS Interface L3 Rollback 
    description: reset Interfaces to default configuration
    job_type: run
    inventory: aws net-demo
    project: network-lab
    playbook: aws_router.yml 
    credential: cisco ec2
    job_tags: rollback, interface
    skip_tags: config
  - name: IOS Router BGP Configuration 
    description: Cisco Router WAN BGP configuration 
    job_type: run
    inventory: aws net-demo
    project: network-lab 
    playbook: aws_router.yml
    credential: cisco ec2
    job_tags: bgp
  - name: IOS Router BGP rollback
    description: Cisco Router WAN BGP configuration 
    job_type: run
    inventory: aws net-demo
    project: network-lab 
    playbook: aws_router.yml
    credential: cisco ec2
    job_tags: bgp,rollback
    skip_tags: config
  - name: IOS Router facts 
    description: gather facts and debug output them
    job_type: run
    inventory: aws net-demo
    project: network-lab
    playbook: aws_router.yml 
    credential: cisco ec2
    job_tags: facts
    verbosity: 2
  - name: IOS show command parser
    description: structured output for IOS commands (genie parser)
    job_type: run
    inventory: aws net-demo
    project: network-lab
    playbook: aws_router.yml 
    credential: cisco ec2
    job_tags: genie
    survey_enabled: yes
    survey_spec: "{{ lookup('file', role_path+'/files/ios_cmd_parser_survey.json') }}"
#    custom_virtualenv: "{{ __tower_venv_path }}/genie"
  - name: F5 Big-IP handle license
    description: install, revoke license
    inventory: aws net-demo
    project: network-lab
    playbook: aws-f5.yml
    job_tags: license
    job_type: run
    survey_enabled: yes
    survey_spec: "{{ lookup('file', role_path+'/files/f5_license_survey.json') }}"
  - name: F5 Big-IP gather facts
    description: get facts from a list
    inventory: aws net-demo
    project: network-lab
    playbook: aws-f5.yml
    job_tags: facts
    job_type: run
    survey_enabled: yes
    verbosity: 2
    survey_spec: "{{ lookup('file', role_path+'/files/f5_facts_survey.json') }}"
  - name: F5 Big-IP load balance webservers
    description: get facts from a list
    inventory: aws net-demo
    project: network-lab
    playbook: aws-f5.yml
    job_tags: balance
    job_type: run
  - name: provisioning webservers
    description: apache and default website
    inventory: aws net-demo
    project: network-lab
    playbook: aws-webserver.yml
    job_type: run
    credential: centos

