---
# workflows.yml

__tower_workflow_template:
  - name: WF 001 - AWS F5 demo provisioning
    description: provisioning and postprov F5 demo on AWS
    survey: "{{ lookup('file', role_path+'/files/aws_lab_count.json') }}"
    survey_enabled: yes
  - name: WF 002 - RM SoT to device intf
    description: provisioning and postprov F5 demo on AWS
    webhook_service: github
    webhook_credential: "{{ tower_github_token }}"
  
__tower_workflow_node:
# WF 001 - AWS F5 demo provisioning
  - identifier: teardown-f5-net-demo
    workflow: WF 001 - AWS F5 demo provisioning
    unified_job_template: AWS EC2 999 - teardown net demo
  - identifier: post-prov-f5-net-demo
    workflow: WF 001 - AWS F5 demo provisioning
    unified_job_template: AWS EC2 002 - post provisioning instances
    failure_nodes:
      - teardown-f5-net-demo
  - identifier: update-inv-f5-ec2-net-demo
    workflow: WF 001 - AWS F5 demo provisioning
    unified_job_template: ec2 net-demo
    success_nodes: 
      - post-prov-f5-net-demo
  - identifier: aws-f5-prov
    workflow: WF 001 - AWS F5 demo provisioning
    unified_job_template: AWS EC2 001 - F5 only setup
    success_nodes:
      - update-inv-f5-ec2-net-demo
    failure_nodes: 
      - teardown-f5-net-demo
# WF 002 - RM SoT to device intf
  - identifier: ios-rm-002
    workflow: WF 002 - RM SoT to device intf
    unified_job_template: IOS RM 002 - push intf config
  - identifier: update-inv-virl-github
    workflow: WF 002 - RM SoT to device intf
    unified_job_template: VIRL github SoT
    success_nodes:
      - ios-rm-002
  - identifier: update-project-demo-sot
    workflow: WF 002 - RM SoT to device intf
    unified_job_template: Network Demo SoT
    success_nodes:
      - update-inv-virl-github

    
