--- 

- include_vars: "{{ role_path }}/vars/credentials.yml"

- name: customize credentials 
  awx.awx.tower_credential:
    tower_host: "https://{{ ansible_host }}"
    tower_username: admin
    tower_password: "{{ tower_setup_admin_password }}"
    validate_certs: no
    organization: Default
    name: "{{ item.name }}"
    kind: "{{ item.kind | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    ssh_key_data: "{{ item.ssh_key_data | default(omit) }}"
    become_password: "{{ item.become_password | default(omit) }}"
    vault_password: "{{ item.vault_password | default(omit) }}"
  loop: "{{ __tower_credentials }}"
  loop_control:
    label: "{{ item.name }}"
  
