--- 

- name: customize credentials 
  tower_credential:
    tower_host: "{{ ansible_host }}"
    tower_username: admin
    tower_password: "{{ tower_setup_admin_password }}"
    validate_certs: no
    organization: Default
    name: "{{ item.name }}"
    kind: "{{ item.kind | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    ssh_key_data: "{{ item.ssh_key_data | default(omit) }}"
  loop: "{{ __tower_credentials }}"
  loop_control:
    label: "{{ item.name }}"
  
