---
# firewall.yml

- name: set ec2_instance variables
  set_fact:
    _instance_type: "{{ ec2_instance_types[_instance_firewall.instance_type] }}"
    _instance: "{{ _instance_firewall | combine(
      { 'security_groups': [ec2_sg.all] }, 
      { 'tag_function': 'firewall' } ) }}"
  tags: [always]

- name: include meta multinet
  include_tasks: "{{ role_path }}/includes/meta_multinet.yml"
  