---

- name: backup Ansible Tower
  shell: "./setup.sh -e 'backup_dest={{ tower_backup_dest }}' -b"
  args:
    chdir: "{{ tower_setup_dir }}/ansible-tower-setup-{{ tower_setup_version }}"
  become: true