---
#
# increase lab count for idempotent instances
ec2_lab_count: 0

ec2_feature_server: false
ec2_feature_firewall: false
ec2_feature_router: false

ec2_wait: no
ec2_pem_key_name: aws-demo
ec2_pem_key_location: ~/.ssh/

ec2_name_prefix: net-demo
ec2_region: eu-central-1
ec2_az: "{{ec2_region}}a"

ec2_vpc_cidr: "172.16.0.0/16"
ec2_vpc_subnets:
  - "172.16.0.0/24"
  - "172.16.1.0/24"
  - "172.16.2.0/24"
#  - "172.16.3.0/24"

ec2_palo_id: "palo-fw-{{ ec2_lab_count}}"
ec2_palo_net0: 0 
ec2_palo_net1: 1

ec2_csr_id: "csr-{{ ec2_lab_count }}"
ec2_csr_list: 
  - networks: [0, 1, 2]
    address: [172.16.0.101, 172.16.1.101, 172.16.2.101] 
  - networks: [0, 1, 3]
    address: [172.16.0.102, 172.16.1.102, 172.16.3.102]

ec2_jumpserver_id: "jumpserver-{{ lab_count }}"
ec2_junos_id: "junos-{{ lab_count }}"

#-----------------------------
# mandatory variables: 
# name: must be unique
# short: taken for unique security group
# instance_type: must be key of ec2_instance_types (in vars/main.yml)
# tag_function: for special post provision features use one of:
#   [tower, gitlab]
# 
# default variables (optional): 
# size: size of instance_type fallbacks to t2.nano
# security_groups: SSH
# volumes: omit
# public_ip: no
# network: 0
# tag_funcion: server
# tag_name: {{ short }}
# tag_os: os tag of instance_type
# pre defined servers (in vars/main.yml):
#   - ec2_linux_server_tower
# 
ec2_linux_server:
  - "{{ ec2_linux_server_tower }}"
#  - "{{ ec2_linux_server_git }}"
  - name: tiny Jump1
    short: tj1
    instance_type: centos7
    network: 1
  - name: tiny Jump 2
    short: tj2
    instance_type: centos7
    public_ip: yes


# networks: (list)
#   - subnet: (subnet list) mandatory
#     address: (ip address) optional

ec2_firewalls: 
  - name: Palo Alto 1
    short: palofw1
    instance_type: palo_fw
    public_ip: yes
    networks:
      - subnet: 0
        address: 172.16.0.99
      - subnet: 1
        address: 172.16.1.99

ec2_routers:
  - name: Cisco CSR 1
    short: csr1
    instance_type: rt_cisco_csr_171
    public_ip: yes
    networks: 
      - subnet: 0 
        address: 172.16.0.200
      - subnet: 1 
        address: 172.16.0.201
      - subnet: 3 
        address: 172.16.0.202

# normally do not turn off 
ec2_feature_vpc: true