---
ansible_connection: network_cli
ansible_network_os: ios

gi2:  "{{ network_interfaces | json_query('[?attachment.device_index==`1`] | [0]') }}"
gi3:  "{{ network_interfaces | json_query('[?attachment.device_index==`2`] | [0]') }}"
bgp_peers: "{{ tags.bgp_peers | default(omit) }}"

interface_config:
    - name: GigabitEthernet2
      ipv4:
        address: "{{ gi2.private_ip_address }}/24"
      description: "WAN interface, id: {{ gi2.network_interface_id }}"
      enabled: True
    
    - name: GigabitEthernet3
      ipv4:
        address: "{{ gi3.private_ip_address }}/24"
      description: "local LAN, ID: {{ gi3.network_interface_id }}"
      enabled: True

ping_destinations: "{{ bgp_peers }}"
ios_bgp_peers: "{{ bgp_peers }}"

ios_bgp_networks: 
  - prefix: "{{ (gi3.private_ip_address + '/24') | ipaddr('network') }}"
    masklen: 24